#!/bin/bash
name=$1
path=$2
host=$3
port=$4

if [ ! -n "$name" ]; then
  name="own"
fi

if [ ! -n "$path" ]; then
  path="/root"
fi

if [ ! -n "$host" ]; then
  port="127.0.0.1"
fi

if [ ! -n "$port" ]; then
  port="83"
fi
echo $name
git clone https://github.com/RManLuo/cloudreve-docker.git /tmp/cloudreve-docker
docker build -t cloudreve /tmp/cloudreve-docker
rm -rf /tmp/cloudreve-docker
docker stop $name
docker rm $name
docker run -d \
	--name $name \
	-p "${host}:${port}:83" \
	-v "${path}/${name}/log:/core/log" \
	-v "${path}/${name}/uploads:/core/uploads" \
	-v "${path}/${name}/db:/core/db" \
	-v "${path}/${name}/etc:/core/etc" \
cloudreve
